import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'hi';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.home': 'Home',
    'header.destinations': 'Destinations',
    'header.itinerary': 'Itinerary',
    'header.marketplace': 'Marketplace',
    'header.chatbot': 'Chatbot',
    'header.dashboard': 'Dashboard',
    'header.jharkhandTourism': 'Jharkhand Tourism',
    'header.ecoPortal': 'Eco & Cultural Portal',
    
    // Quick Search
    'quickSearch.title': 'Start Your Jharkhand Adventure',
    'quickSearch.tripType': 'Type of Trip',
    'quickSearch.duration': 'Duration',
    'quickSearch.budget': 'Budget',
    'quickSearch.generate': 'Generate Itinerary',
    'quickSearch.selectType': 'Select type',
    'quickSearch.adventure': 'Adventure',
    'quickSearch.nature': 'Nature',
    'quickSearch.culture': 'Culture',
    'quickSearch.relax': 'Relax',
    'quickSearch.selectDays': 'Select days',
    'quickSearch.selectBudget': 'Select budget',
    'quickSearch.budgetLow': 'Low (₹5,000 - ₹15,000)',
    'quickSearch.budgetMedium': 'Medium (₹15,000 - ₹30,000)',
    'quickSearch.budgetHigh': 'High (₹30,000+)',
    
    // Home Page
    'home.welcome': 'Welcome to Jharkhand',
    'home.subtitle': 'Land of Forests',
    'home.description': 'Discover the rich cultural heritage, pristine natural beauty, and warm hospitality of Jharkhand. From ancient temples to cascading waterfalls, every corner tells a story.',
    'home.exploreDestinations': 'Explore Destinations',
    'home.planTrip': 'Plan Your Trip',
    'home.featuredDestinations': 'Featured Destinations',
    'home.exploreMore': 'Explore More',
    
    // Features
    'features.title': 'Why Choose Jharkhand Tourism?',
    'features.culturalHeritage': 'Cultural Heritage',
    'features.culturalDesc': 'Experience rich tribal culture, traditional arts, and ancient temples',
    'features.naturalBeauty': 'Natural Beauty',
    'features.naturalDesc': 'Explore pristine waterfalls, dense forests, and scenic hill stations',
    'features.adventure': 'Adventure Activities',
    'features.adventureDesc': 'Trek through forests, rock climbing, and wildlife safaris',
    'features.localCuisine': 'Local Cuisine',
    'features.cuisineDesc': 'Taste authentic tribal dishes and traditional Jharkhandi flavors',
    
    // Destinations Data
    'dest.netarhat.name': 'Netarhat',
    'dest.netarhat.tagline': 'Queen of Chotanagpur Plateau',
    'dest.netarhat.story': 'Famous for its sunrise views and cool climate, Netarhat is a perfect hill station escape.',
    'dest.netarhat.bestSeason': 'October - March',
    'dest.netarhat.distance': '156 km from Ranchi',
    'dest.netarhat.activities.sunrise': 'Sunrise Views',
    'dest.netarhat.activities.forest': 'Pine Forest Walk',
    'dest.netarhat.activities.photography': 'Photography',
    
    'dest.hundru.name': 'Hundru Falls',
    'dest.hundru.tagline': 'Thundering Beauty',
    'dest.hundru.story': 'A spectacular 98-meter waterfall where Subarnarekha river creates nature\'s masterpiece.',
    'dest.hundru.bestSeason': 'July - January',
    'dest.hundru.distance': '45 km from Ranchi',
    'dest.hundru.activities.photography': 'Waterfall Photography',
    'dest.hundru.activities.trekking': 'Trekking',
    'dest.hundru.activities.climbing': 'Rock Climbing',
    
    'dest.betla.name': 'Betla National Park',
    'dest.betla.tagline': 'Wildlife Paradise',
    'dest.betla.story': 'Home to tigers, elephants and diverse wildlife in the Palamau Tiger Reserve.',
    'dest.betla.bestSeason': 'November - April',
    'dest.betla.distance': '170 km from Ranchi',
    'dest.betla.activities.safari': 'Safari',
    'dest.betla.activities.birdWatching': 'Bird Watching',
    'dest.betla.activities.photography': 'Nature Photography',
    
    'dest.deoghar.name': 'Deoghar',
    'dest.deoghar.tagline': 'Abode of Gods',
    'dest.deoghar.story': 'Sacred temple town famous for Baba Baidyanath Dham, one of the twelve Jyotirlingas.',
    'dest.deoghar.bestSeason': 'October - March',
    'dest.deoghar.distance': '250 km from Ranchi',
    'dest.deoghar.activities.temple': 'Temple Visits',
    'dest.deoghar.activities.spiritual': 'Spiritual Walk',
    'dest.deoghar.activities.cultural': 'Cultural Tours',
    
    // Destination Detail Page
    'destDetail.notFound': 'Destination Not Found',
    'destDetail.notFoundDesc': 'The destination you\'re looking for doesn\'t exist.',
    'destDetail.backHome': 'Back to Home',
    'destDetail.addToItinerary': 'Add to Itinerary',
    'destDetail.addedToItinerary': 'Added to Itinerary',
    'destDetail.viewItinerary': 'View Itinerary →',
    'destDetail.currentWeather': 'Current Weather',
    'destDetail.temperature': 'Temperature',
    'destDetail.humidity': 'Humidity',
    'destDetail.windSpeed': 'Wind Speed',
    'destDetail.bestTime': 'Best Time',
    'destDetail.about': 'About',
    'destDetail.highlights': 'Key Highlights',
    'destDetail.videos': 'Videos',
    'destDetail.video': 'Video',
    'destDetail.openInMaps': 'Open in Google Maps',
    'destDetail.reviews': 'Customer Reviews',
    'destDetail.review': 'review',
    'destDetail.reviews_plural': 'reviews',
    'destDetail.guides': 'Local Guides',
    'destDetail.guidesDesc': 'Expert local guides to enhance your experience',
    'destDetail.experience': 'experience',
    'destDetail.verified': 'Verified',
    'destDetail.unverified': 'Unverified',
    'destDetail.pending': 'Pending',
    'destDetail.languages': 'Languages:',
    'destDetail.specialties': 'Specialties:',
    'destDetail.perHour': 'per hour',
    'destDetail.bookNow': 'Book Now',
    'destDetail.contact': 'Contact',
    'destDetail.eateries': 'Local Eateries',
    'destDetail.transport': 'How to Reach',
    'destDetail.duration': 'Duration:',
    'destDetail.cost': 'Cost:',
    'destDetail.products': 'Famous Local Products',
    'destDetail.viewInMarketplace': 'View in Marketplace',
    
    // Itinerary Planner
    'itinerary.title': 'AI-Powered Itinerary Planner',
    'itinerary.subtitle': 'Let our AI create a personalized travel experience just for you',
    'itinerary.planJourney': 'Plan Your Journey',
    'itinerary.startingCity': 'Starting City',
    'itinerary.startingCityPlaceholder': 'e.g., Ranchi, Jamshedpur',
    'itinerary.travelDates': 'Travel Dates',
    'itinerary.duration': 'Duration',
    'itinerary.selectDuration': 'Select duration',
    'itinerary.1day': '1 Day',
    'itinerary.2to3days': '2-3 Days',
    'itinerary.4to5days': '4-5 Days',
    'itinerary.6to7days': '6-7 Days',
    'itinerary.interests': 'Your Interests',
    'itinerary.desiredPlaces': 'Desired Places to Visit',
    'itinerary.optional': '(Optional)',
    'itinerary.desiredPlacesDesc': 'Know specific places you want to visit? Add them here for a more personalized itinerary.',
    'itinerary.popularPlaces': '💡 Popular places in Jharkhand: Hundru Falls, Netarhat, Betla National Park, Ranchi Zoo, Dassam Falls, Patratu Valley',
    'itinerary.addPlace': 'Add a desired place (e.g., Hundru Falls, Ranchi Zoo)',
    'itinerary.groupType': 'Group Type',
    'itinerary.selectGroupType': 'Select group type',
    'itinerary.solo': 'Solo Travel',
    'itinerary.couple': 'Couple',
    'itinerary.family': 'Family with Kids',
    'itinerary.friends': 'Friends Group',
    'itinerary.generatePlan': 'Generate Plan',
    'itinerary.generating': 'Generating Your Perfect Trip...',
    'itinerary.willAppear': 'Your Itinerary Will Appear Here',
    'itinerary.fillForm': 'Fill out the form and click "Generate Plan" to see your personalized journey',
    'itinerary.yourJourney': 'Your Jharkhand Journey',
    'itinerary.downloadPDF': 'Download PDF',
    'itinerary.aiGenerated': 'AI-Generated Itinerary',
    'itinerary.day': 'Day',
    'itinerary.whyRecommended': 'Why we recommended this:',
    
    // Destination Explorer
    'explorer.title': 'Destination Explorer',
    'explorer.subtitle': 'Discover amazing places across Jharkhand with interactive maps and detailed guides',
    'explorer.interactiveMap': 'Interactive Map',
    'explorer.clickPins': 'Click pins to explore',
    'explorer.touristDestinations': 'Tourist Destinations',
    'explorer.explore': 'Explore',
    
    // Marketplace
    'marketplace.title': 'Jharkhand Marketplace',
    'marketplace.subtitle': 'Discover authentic local products, connect with skilled artisans, and support the tribal economy',
    'marketplace.searchProducts': 'Search products, artisans, or categories...',
    'marketplace.categories': 'Categories',
    'marketplace.all': 'All',
    'marketplace.handicrafts': 'Handicrafts',
    'marketplace.textiles': 'Textiles',
    'marketplace.jewelry': 'Jewelry',
    'marketplace.pottery': 'Pottery',
    'marketplace.food': 'Food & Spices',
    'marketplace.verified': 'Verified',
    'marketplace.unverified': 'Unverified',
    'marketplace.rating': 'Rating',
    'marketplace.addToCart': 'Add to Cart',
    'marketplace.buyNow': 'Buy Now',
    'marketplace.viewDetails': 'View Details',
    'marketplace.artisan': 'Artisan',
    'marketplace.location': 'Location',
    'marketplace.inStock': 'In Stock',
    'marketplace.outOfStock': 'Out of Stock',
    
    // Chatbot
    'chatbot.title': 'Tour Companion Chatbot',
    'chatbot.subtitle': 'Get instant answers about Jharkhand tourism, local culture, and travel tips',
    'chatbot.guideName': 'Jharkhand Tour Guide',
    'chatbot.status': 'Online • Always ready to help',
    'chatbot.placeholder': 'Ask about Jharkhand tourism...',
    'chatbot.quickQuestions': 'Quick Questions',
    'chatbot.howToReach': 'How to reach Netarhat?',
    'chatbot.localFood': 'Local food options?',
    'chatbot.emergency': 'Emergency contacts',
    'chatbot.bestTime': 'Best time to visit?',
    'chatbot.tribalCulture': 'Tribal culture tours',
    'chatbot.safari': 'Wildlife safari bookings',
    'chatbot.proTip': 'Pro Tip',
    'chatbot.proTipDesc': 'Ask me in Hindi or your local language! I can help in multiple languages.',
    'chatbot.welcome': 'Hello! I\'m your Jharkhand tour companion. How can I help you plan your trip? 🌲',
    
    // Dashboard
    'dashboard.title': 'Tourism Dashboard',
    'dashboard.subtitle': 'Your complete travel companion for Jharkhand',
    'dashboard.profile': 'User Profile',
    'dashboard.preferences': 'Preferences',
    'dashboard.startPlanning': 'Start Planning a Trip',
    'dashboard.totalTrips': 'Total Trips',
    'dashboard.placesVisited': 'Places Visited',
    'dashboard.guidesBooked': 'Guides Booked',
    'dashboard.itinerariesWishlist': 'Saved Itineraries / Wishlist',
    'dashboard.days': 'days',
    'dashboard.open': 'Open',
    'dashboard.platformAnalytics': 'Platform Analytics',
    'dashboard.totalItineraries': 'Total Itineraries',
    'dashboard.activeGuides': 'Active Guides',
    'dashboard.verifiedArtisans': 'Verified Artisans',
    'dashboard.satisfactionRate': 'Satisfaction Rate',
    'dashboard.topDestinations': 'Top Destinations',
    'dashboard.culturalEvents': 'Cultural Events Calendar',
    'dashboard.add': 'Add',
    'dashboard.safetyGuidelines': 'Safety Guidelines (Jharkhand)',
    'dashboard.safetyTip1': 'Respect local customs and seek permission before photographs.',
    'dashboard.safetyTip2': 'Travel with registered guides in remote forest areas.',
    'dashboard.safetyTip3': 'Keep emergency numbers handy and share itinerary with family.',
    'dashboard.safetyTip4': 'Carry cash for rural regions; connectivity may be limited.',
    'dashboard.emergencyContacts': 'Emergency Contacts',
    'dashboard.police': 'Police',
    'dashboard.ambulance': 'Ambulance',
    'dashboard.womenHelpline': 'Women Helpline',
    'dashboard.rateServices': 'Rate Your Guides, Homestays, and Artisans',
    'dashboard.submitRating': 'Submit Rating',
    'dashboard.markHonest': 'Mark as Honest',
    'dashboard.markedHonest': 'Marked Honest ✅',
    'dashboard.giveBadge': 'Give Community Badge',
    'dashboard.badgeGranted': 'Badge Granted',
    'dashboard.shareExperience': 'Share your experience (optional)',
    'dashboard.recentActivity': 'Recent Activity',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.destinations': 'Destinations',
    'footer.support': 'Support',
    'footer.faq': 'FAQ',
    'footer.help': 'Help Center',
    'footer.feedback': 'Feedback',
    'footer.connect': 'Connect With Us',
    'footer.newsletter': 'Subscribe to our newsletter for travel tips and updates',
    'footer.email': 'Your email address',
    'footer.subscribe': 'Subscribe',
    'footer.copyright': '© 2025 Jharkhand Tourism. All rights reserved.',
    'footer.madeWith': 'Made with ❤️ for Jharkhand',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.comment': 'Comment',
    'common.follow': 'Follow',
    'common.more': 'More',
    'common.less': 'Less',
    'common.showMore': 'Show More',
    'common.showLess': 'Show Less',
  },
  hi: {
    // Header
    'header.home': 'होम',
    'header.destinations': 'गंतव्य',
    'header.itinerary': 'यात्रा योजना',
    'header.marketplace': 'बाजार',
    'header.chatbot': 'चैटबॉट',
    'header.dashboard': 'डैशबोर्ड',
    'header.jharkhandTourism': 'झारखंड पर्यटन',
    'header.ecoPortal': 'पर्यावरण और सांस्कृतिक पोर्टल',
    
    // Quick Search
    'quickSearch.title': 'अपना झारखंड साहसिक कार्य शुरू करें',
    'quickSearch.tripType': 'यात्रा का प्रकार',
    'quickSearch.duration': 'अवधि',
    'quickSearch.budget': 'बजट',
    'quickSearch.generate': 'यात्रा योजना बनाएं',
    'quickSearch.selectType': 'प्रकार चुनें',
    'quickSearch.adventure': 'साहसिक',
    'quickSearch.nature': 'प्रकृति',
    'quickSearch.culture': 'संस्कृति',
    'quickSearch.relax': 'आराम',
    'quickSearch.selectDays': 'दिन चुनें',
    'quickSearch.selectBudget': 'बजट चुनें',
    'quickSearch.budgetLow': 'कम (₹5,000 - ₹15,000)',
    'quickSearch.budgetMedium': 'मध्यम (₹15,000 - ₹30,000)',
    'quickSearch.budgetHigh': 'उच्च (₹30,000+)',
    
    // Home Page
    'home.welcome': 'झारखंड में आपका स्वागत है',
    'home.subtitle': 'वनों की भूमि',
    'home.description': 'झारखंड की समृद्ध सांस्कृतिक विरासत, प्राचीन प्राकृतिक सुंदरता और गर्मजोशी से भरी आतिथ्य की खोज करें। प्राचीन मंदिरों से लेकर झरनों तक, हर कोना एक कहानी कहता है।',
    'home.exploreDestinations': 'गंतव्यों का अन्वेषण करें',
    'home.planTrip': 'अपनी यात्रा की योजना बनाएं',
    'home.featuredDestinations': 'विशेष गंतव्य',
    'home.exploreMore': 'और देखें',
    
    // Features
    'features.title': 'झारखंड पर्यटन क्यों चुनें?',
    'features.culturalHeritage': 'सांस्कृतिक विरासत',
    'features.culturalDesc': 'समृद्ध आदिवासी संस्कृति, पारंपरिक कलाओं और प्राचीन मंदिरों का अनुभव करें',
    'features.naturalBeauty': 'प्राकृतिक सुंदरता',
    'features.naturalDesc': 'प्राचीन झरनों, घने जंगलों और सुंदर पहाड़ी स्टेशनों का अन्वेषण करें',
    'features.adventure': 'साहसिक गतिविधियां',
    'features.adventureDesc': 'जंगलों में ट्रेकिंग, चट्टान पर चढ़ना और वन्यजीव सफारी',
    'features.localCuisine': 'स्थानीय व्यंजन',
    'features.cuisineDesc': 'प्रामाणिक आदिवासी व्यंजनों और पारंपरिक झारखंडी स्वादों का स्वाद लें',
    
    // Destinations Data
    'dest.netarhat.name': 'नेतरहाट',
    'dest.netarhat.tagline': 'छोटानागपुर पठार की रानी',
    'dest.netarhat.story': 'सूर्योदय के दृश्यों और ठंडी जलवायु के लिए प्रसिद्ध, नेतरहाट एक आदर्श हिल स्टेशन है।',
    'dest.netarhat.bestSeason': 'अक्टूबर - मार्च',
    'dest.netarhat.distance': 'रांची से 156 किमी',
    'dest.netarhat.activities.sunrise': 'सूर्योदय के दृश्य',
    'dest.netarhat.activities.forest': 'पाइन वन सैर',
    'dest.netarhat.activities.photography': 'फोटोग्राफी',
    
    'dest.hundru.name': 'हुंडरू जलप्रपात',
    'dest.hundru.tagline': 'गर्जना करती सुंदरता',
    'dest.hundru.story': 'एक शानदार 98 मीटर का जलप्रपात जहां सुवर्णरेखा नदी प्रकृति की कृति बनाती है।',
    'dest.hundru.bestSeason': 'जुलाई - जनवरी',
    'dest.hundru.distance': 'रांची से 45 किमी',
    'dest.hundru.activities.photography': 'जलप्रपात फोटोग्राफी',
    'dest.hundru.activities.trekking': 'ट्रेकिंग',
    'dest.hundru.activities.climbing': 'चट्टान चढ़ाई',
    
    'dest.betla.name': 'बेतला राष्ट्रीय पार्क',
    'dest.betla.tagline': 'वन्यजीव स्वर्ग',
    'dest.betla.story': 'पलामू टाइगर रिजर्व में बाघों, हाथियों और विविध वन्यजीवों का घर।',
    'dest.betla.bestSeason': 'नवंबर - अप्रैल',
    'dest.betla.distance': 'रांची से 170 किमी',
    'dest.betla.activities.safari': 'सफारी',
    'dest.betla.activities.birdWatching': 'पक्षी देखना',
    'dest.betla.activities.photography': 'प्रकृति फोटोग्राफी',
    
    'dest.deoghar.name': 'देवघर',
    'dest.deoghar.tagline': 'देवताओं का निवास',
    'dest.deoghar.story': 'बाबा बैद्यनाथ धाम के लिए प्रसिद्ध पवित्र मंदिर शहर, जो बारह ज्योतिर्लिंगों में से एक है।',
    'dest.deoghar.bestSeason': 'अक्टूबर - मार्च',
    'dest.deoghar.distance': 'रांची से 250 किमी',
    'dest.deoghar.activities.temple': 'मंदिर दर्शन',
    'dest.deoghar.activities.spiritual': 'आध्यात्मिक यात्रा',
    'dest.deoghar.activities.cultural': 'सांस्कृतिक पर्यटन',
    
    // Destination Detail Page
    'destDetail.notFound': 'गंतव्य नहीं मिला',
    'destDetail.notFoundDesc': 'आप जो गंतव्य खोज रहे हैं वह मौजूद नहीं है।',
    'destDetail.backHome': 'होम पर वापस जाएं',
    'destDetail.addToItinerary': 'यात्रा योजना में जोड़ें',
    'destDetail.addedToItinerary': 'यात्रा योजना में जोड़ा गया',
    'destDetail.viewItinerary': 'यात्रा योजना देखें →',
    'destDetail.currentWeather': 'वर्तमान मौसम',
    'destDetail.temperature': 'तापमान',
    'destDetail.humidity': 'नमी',
    'destDetail.windSpeed': 'हवा की गति',
    'destDetail.bestTime': 'सबसे अच्छा समय',
    'destDetail.about': 'के बारे में',
    'destDetail.highlights': 'मुख्य विशेषताएं',
    'destDetail.videos': 'वीडियो',
    'destDetail.video': 'वीडियो',
    'destDetail.openInMaps': 'गूगल मैप्स में खोलें',
    'destDetail.reviews': 'ग्राहक समीक्षाएं',
    'destDetail.review': 'समीक्षा',
    'destDetail.reviews_plural': 'समीक्षाएं',
    'destDetail.guides': 'स्थानीय गाइड',
    'destDetail.guidesDesc': 'आपके अनुभव को बढ़ाने के लिए विशेषज्ञ स्थानीय गाइड',
    'destDetail.experience': 'अनुभव',
    'destDetail.verified': 'सत्यापित',
    'destDetail.unverified': 'असत्यापित',
    'destDetail.pending': 'लंबित',
    'destDetail.languages': 'भाषाएं:',
    'destDetail.specialties': 'विशेषताएं:',
    'destDetail.perHour': 'प्रति घंटा',
    'destDetail.bookNow': 'अभी बुक करें',
    'destDetail.contact': 'संपर्क',
    'destDetail.eateries': 'स्थानीय भोजनालय',
    'destDetail.transport': 'कैसे पहुंचें',
    'destDetail.duration': 'अवधि:',
    'destDetail.cost': 'लागत:',
    'destDetail.products': 'प्रसिद्ध स्थानीय उत्पाद',
    'destDetail.viewInMarketplace': 'बाजार में देखें',
    
    // Itinerary Planner
    'itinerary.title': 'एआई-संचालित यात्रा योजनाकार',
    'itinerary.subtitle': 'हमारी एआई आपके लिए एक व्यक्तिगत यात्रा अनुभव बनाने दें',
    'itinerary.planJourney': 'अपनी यात्रा की योजना बनाएं',
    'itinerary.startingCity': 'प्रारंभिक शहर',
    'itinerary.startingCityPlaceholder': 'उदा., रांची, जमशेदपुर',
    'itinerary.travelDates': 'यात्रा की तारीखें',
    'itinerary.duration': 'अवधि',
    'itinerary.selectDuration': 'अवधि चुनें',
    'itinerary.1day': '1 दिन',
    'itinerary.2to3days': '2-3 दिन',
    'itinerary.4to5days': '4-5 दिन',
    'itinerary.6to7days': '6-7 दिन',
    'itinerary.interests': 'आपकी रुचियां',
    'itinerary.desiredPlaces': 'जाने की इच्छा वाले स्थान',
    'itinerary.optional': '(वैकल्पिक)',
    'itinerary.desiredPlacesDesc': 'कोई विशिष्ट स्थान जहां आप जाना चाहते हैं? अधिक व्यक्तिगत यात्रा योजना के लिए उन्हें यहां जोड़ें।',
    'itinerary.popularPlaces': '💡 झारखंड में लोकप्रिय स्थान: हुंडरू जलप्रपात, नेतरहाट, बेतला राष्ट्रीय पार्क, रांची चिड़ियाघर, दशम जलप्रपात, पत्रातू घाटी',
    'itinerary.addPlace': 'एक इच्छित स्थान जोड़ें (उदा., हुंडरू जलप्रपात, रांची चिड़ियाघर)',
    'itinerary.groupType': 'समूह का प्रकार',
    'itinerary.selectGroupType': 'समूह का प्रकार चुनें',
    'itinerary.solo': 'अकेली यात्रा',
    'itinerary.couple': 'जोड़ा',
    'itinerary.family': 'बच्चों के साथ परिवार',
    'itinerary.friends': 'दोस्तों का समूह',
    'itinerary.generatePlan': 'योजना बनाएं',
    'itinerary.generating': 'आपकी परफेक्ट ट्रिप बनाई जा रही है...',
    'itinerary.willAppear': 'आपकी यात्रा योजना यहां दिखाई देगी',
    'itinerary.fillForm': 'फॉर्म भरें और "योजना बनाएं" पर क्लिक करके अपनी व्यक्तिगत यात्रा देखें',
    'itinerary.yourJourney': 'आपकी झारखंड यात्रा',
    'itinerary.downloadPDF': 'पीडीएफ डाउनलोड करें',
    'itinerary.aiGenerated': 'एआई-जनरेटेड यात्रा योजना',
    'itinerary.day': 'दिन',
    'itinerary.whyRecommended': 'हमने यह क्यों सुझाया:',
    
    // Destination Explorer
    'explorer.title': 'गंतव्य अन्वेषक',
    'explorer.subtitle': 'इंटरैक्टिव मानचित्र और विस्तृत गाइड के साथ झारखंड में अद्भुत स्थानों की खोज करें',
    'explorer.interactiveMap': 'इंटरैक्टिव मानचित्र',
    'explorer.clickPins': 'अन्वेषण के लिए पिन पर क्लिक करें',
    'explorer.touristDestinations': 'पर्यटन स्थल',
    'explorer.explore': 'अन्वेषण करें',
    
    // Marketplace
    'marketplace.title': 'झारखंड बाजार',
    'marketplace.subtitle': 'प्रामाणिक स्थानीय उत्पादों की खोज करें, कुशल कारीगरों से जुड़ें, और आदिवासी अर्थव्यवस्था का समर्थन करें',
    'marketplace.searchProducts': 'उत्पाद, कारीगर, या श्रेणियां खोजें...',
    'marketplace.categories': 'श्रेणियां',
    'marketplace.all': 'सभी',
    'marketplace.handicrafts': 'हस्तशिल्प',
    'marketplace.textiles': 'वस्त्र',
    'marketplace.jewelry': 'आभूषण',
    'marketplace.pottery': 'मिट्टी के बर्तन',
    'marketplace.food': 'भोजन और मसाले',
    'marketplace.verified': 'सत्यापित',
    'marketplace.unverified': 'असत्यापित',
    'marketplace.rating': 'रेटिंग',
    'marketplace.addToCart': 'कार्ट में जोड़ें',
    'marketplace.buyNow': 'अभी खरीदें',
    'marketplace.viewDetails': 'विवरण देखें',
    'marketplace.artisan': 'कारीगर',
    'marketplace.location': 'स्थान',
    'marketplace.inStock': 'स्टॉक में',
    'marketplace.outOfStock': 'स्टॉक खत्म',
    
    // Chatbot
    'chatbot.title': 'टूर कंपेनियन चैटबॉट',
    'chatbot.subtitle': 'झारखंड पर्यटन, स्थानीय संस्कृति और यात्रा युक्तियों के बारे में तुरंत उत्तर प्राप्त करें',
    'chatbot.guideName': 'झारखंड टूर गाइड',
    'chatbot.status': 'ऑनलाइन • हमेशा मदद के लिए तैयार',
    'chatbot.placeholder': 'झारखंड पर्यटन के बारे में पूछें...',
    'chatbot.quickQuestions': 'त्वरित प्रश्न',
    'chatbot.howToReach': 'नेतरहाट कैसे पहुंचें?',
    'chatbot.localFood': 'स्थानीय भोजन विकल्प?',
    'chatbot.emergency': 'आपातकालीन संपर्क',
    'chatbot.bestTime': 'घूमने का सबसे अच्छा समय?',
    'chatbot.tribalCulture': 'आदिवासी संस्कृति पर्यटन',
    'chatbot.safari': 'वन्यजीव सफारी बुकिंग',
    'chatbot.proTip': 'प्रो टिप',
    'chatbot.proTipDesc': 'मुझसे हिंदी या अपनी स्थानीय भाषा में पूछें! मैं कई भाषाओं में मदद कर सकता हूं।',
    'chatbot.welcome': 'नमस्ते! मैं आपका झारखंड टूर कंपेनियन हूं। मैं आपकी यात्रा की योजना बनाने में कैसे मदद कर सकता हूं? 🌲',
    
    // Dashboard
    'dashboard.title': 'पर्यटन डैशबोर्ड',
    'dashboard.subtitle': 'झारखंड के लिए आपका संपूर्ण यात्रा साथी',
    'dashboard.profile': 'उपयोगकर्ता प्रोफ़ाइल',
    'dashboard.preferences': 'प्राथमिकताएं',
    'dashboard.startPlanning': 'यात्रा की योजना शुरू करें',
    'dashboard.totalTrips': 'कुल यात्राएं',
    'dashboard.placesVisited': 'देखे गए स्थान',
    'dashboard.guidesBooked': 'बुक किए गए गाइड',
    'dashboard.itinerariesWishlist': 'सहेजी गई यात्रा योजनाएं / विशलिस्ट',
    'dashboard.days': 'दिन',
    'dashboard.open': 'खोलें',
    'dashboard.platformAnalytics': 'प्लेटफॉर्म एनालिटिक्स',
    'dashboard.totalItineraries': 'कुल यात्रा योजनाएं',
    'dashboard.activeGuides': 'सक्रिय गाइड',
    'dashboard.verifiedArtisans': 'सत्यापित कारीगर',
    'dashboard.satisfactionRate': 'संतुष्टि दर',
    'dashboard.topDestinations': 'शीर्ष गंतव्य',
    'dashboard.culturalEvents': 'सांस्कृतिक कार्यक्रम कैलेंडर',
    'dashboard.add': 'जोड़ें',
    'dashboard.safetyGuidelines': 'सुरक्षा दिशानिर्देश (झारखंड)',
    'dashboard.safetyTip1': 'स्थानीय रीति-रिवाजों का सम्मान करें और फोटो लेने से पहले अनुमति लें।',
    'dashboard.safetyTip2': 'दूरदराज के वन क्षेत्रों में पंजीकृत गाइड के साथ यात्रा करें।',
    'dashboard.safetyTip3': 'आपातकालीन नंबर हमेशा साथ रखें और यात्रा योजना परिवार के साथ साझा करें।',
    'dashboard.safetyTip4': 'ग्रामीण क्षेत्रों के लिए नकदी ले जाएं; कनेक्टिविटी सीमित हो सकती है।',
    'dashboard.emergencyContacts': 'आपातकालीन संपर्क',
    'dashboard.police': 'पुलिस',
    'dashboard.ambulance': 'एम्बुलेंस',
    'dashboard.womenHelpline': 'महिला हेल्पलाइन',
    'dashboard.rateServices': 'अपने गाइड, होमस्टे और कारीगरों को रेट करें',
    'dashboard.submitRating': 'रेटिंग सबमिट करें',
    'dashboard.markHonest': 'ईमानदार के रूप में चिह्नित करें',
    'dashboard.markedHonest': 'ईमानदार चिह्नित ✅',
    'dashboard.giveBadge': 'कम्यूनिटी बैज दें',
    'dashboard.badgeGranted': 'बैज प्रदान किया गया',
    'dashboard.shareExperience': 'अपना अनुभव साझा करें (वैकल्पिक)',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    
    // Footer
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.about': 'के बारे में',
    'footer.contact': 'संपर्क',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.destinations': 'गंतव्य',
    'footer.support': 'सहायता',
    'footer.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'footer.help': 'सहायता केंद्र',
    'footer.feedback': 'फीडबैक',
    'footer.connect': 'हमसे जुड़ें',
    'footer.newsletter': 'यात्रा युक्तियों और अपडेट के लिए हमारे न्यूजलेटर की सदस्यता लें',
    'footer.email': 'आपका ईमेल पता',
    'footer.subscribe': 'सदस्यता लें',
    'footer.copyright': '© 2025 झारखंड पर्यटन। सभी अधिकार सुरक्षित।',
    'footer.madeWith': 'झारखंड के लिए ❤️ के साथ बनाया गया',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.retry': 'पुनः प्रयास करें',
    'common.back': 'वापस',
    'common.next': 'आगे',
    'common.previous': 'पिछला',
    'common.close': 'बंद करें',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.view': 'देखें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.share': 'साझा करें',
    'common.like': 'पसंद',
    'common.comment': 'टिप्पणी',
    'common.follow': 'फॉलो करें',
    'common.more': 'और',
    'common.less': 'कम',
    'common.showMore': 'और दिखाएं',
    'common.showLess': 'कम दिखाएं',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'en' | 'hi'>(() => {
    const saved = localStorage.getItem('language');
    return (saved as 'en' | 'hi') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}